# .prettierrc.toml
plugins = ["prettier-plugin-svelte"]

trailingComma = "all"
tabWidth = 2
semi = true
singleQuote = true

[[overrides]]
files = "*.svelte"
options = { parser = "svelte" }

